CREATE DATABASE HiKanban;
USE HiKanban;

CREATE TABLE User (
idUser INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
email VARCHAR(320) NOT NULL UNIQUE,
password VARCHAR(45) NOT NULL
);

CREATE TABLE Block (
idBlock INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
color CHAR(7),
isFavorite TINYINT NOT NULL DEFAULT 0,
fkUser INT,
CONSTRAINT fkUserBlock FOREIGN KEY (fkUser) REFERENCES User(idUser),
CONSTRAINT chkColor CHECK (color LIKE '#%')
);

CREATE TABLE Task (
idTask INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
description VARCHAR(200) NULL,
endDate DATETIME,
fkBlock INT,
fkUser INT,
status VARCHAR(12),
CONSTRAINT fkBlockTask FOREIGN KEY (fkBlock) REFERENCES Block(idBlock),
CONSTRAINT fkUserTask FOREIGN KEY (fkUser) REFERENCES User(idUser),
CONSTRAINT chkStatus CHECK (status IN('TO_DO', 'IN_PROGRESS', 'FINISHED'))
);
